package com.mine.engine.controller;

import com.mine.engine.model.Market;
import com.mine.engine.model.User;
import com.mine.engine.service.UserService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

/**
 * REST Controller for Account/User APIs.
 * Provides endpoints to manage user accounts and balances.
 */
@Slf4j
@RestController
@RequestMapping("/api/account")
@CrossOrigin(origins = "*")
public class AccountController {

    private final Map<UUID, User> userData;
    private final UserService  userService;

    public AccountController(Map<UUID, User> userData, UserService userService) {
        this.userData = userData;
        this.userService = userService;
    }

    /**
     * Get user balance and holdings.
     * GET /api/account/{userId}/balance
     */
    @GetMapping("/{userId}/balance")
    public ResponseEntity<BalanceResponse> getBalance(@PathVariable UUID userId) {
        User user = userData.get(userId);
        
        if (user == null) {
            log.warn("User not found: {}", userId);
            return ResponseEntity.notFound().build();
        }

        BalanceResponse response = new BalanceResponse();
        response.setUserId(userId);
        response.setCashBalance(user.getCash());
        response.setHoldings(new HashMap<>(user.getMarkets()));
        
        return ResponseEntity.ok(response);
    }

    /**
     * Create or register a new user account.
     * POST /api/account/register
     * UUID is generated by UserService.addUser() and returned in response.
     * Do not send userId in request - it will be generated by the database.
     */
    @PostMapping("/register")
    public ResponseEntity<BalanceResponse> registerUser(@RequestBody RegisterUserRequest request) {
        // Ignore userId if sent - generate new UUID from database
        UUID userID = userService.addUser(request.getInitialBalance());
        log.info("User {} registered successfully with initial balance {}", userID, request.getInitialBalance());
        
        BalanceResponse response = new BalanceResponse();
        response.setUserId(userID);
        response.setCashBalance(request.getInitialBalance());

        return ResponseEntity.ok(response);
    }

    /**
     * Check if user exists.
     * GET /api/account/{userId}/exists
     */
    @GetMapping("/{userId}/exists")
    public ResponseEntity<Map<String, Boolean>> checkUserExists(@PathVariable UUID userId) {
        Map<String, Boolean> response = new HashMap<>();
        response.put("exists", userData.containsKey(userId));
        return ResponseEntity.ok(response);
    }

    /**
     * Get all users (for admin/debugging).
     * GET /api/account/all
     */
    @GetMapping("/all")
    public ResponseEntity<Map<String, Object>> getAllUsers() {
        Map<String, Object> response = new HashMap<>();
        response.put("count", userData.size());
        response.put("userIds", userData.keySet());
        return ResponseEntity.ok(response);
    }

    /**
     * Add funds to user account (for testing/simulation).
     * POST /api/account/{userId}/deposit
     */
    @PostMapping("/{userId}/deposit")
    public ResponseEntity<BalanceResponse> deposit(
            @PathVariable UUID userId,
            @RequestBody DepositRequest request) {
        
        User user = userData.get(userId);
        if (user == null) {
            return ResponseEntity.notFound().build();
        }

        user.addCash(request.getAmount());
        log.info("Deposited {} to user {}, new balance: {}", request.getAmount(), userId, user.getCash());

        BalanceResponse response = new BalanceResponse();
        response.setUserId(userId);
        response.setCashBalance(user.getCash());
        response.setHoldings(user.getMarkets());
        
        return ResponseEntity.ok(response);
    }

    /**
     * Add BTC holdings to user account (for bot balance replenishment).
     * POST /api/account/{userId}/add-btc
     */
    @PostMapping("/{userId}/add-btc")
    public ResponseEntity<BalanceResponse> addBtc(
            @PathVariable UUID userId,
            @RequestBody AddBtcRequest request) {
        
        User user = userData.get(userId);
        if (user == null) {
            return ResponseEntity.notFound().build();
        }

        // Add BTC holdings
        long currentBtc = user.getMarkets().getOrDefault(Market.BTC, 0L);
        user.getMarkets().put(Market.BTC, currentBtc + request.getAmount());
        
        log.info("Added {} BTC to user {}, new BTC holdings: {}", 
                request.getAmount(), userId, user.getMarkets().get(Market.BTC));

        BalanceResponse response = new BalanceResponse();
        response.setUserId(userId);
        response.setCashBalance(user.getCash());
        response.setHoldings(user.getMarkets());
        
        return ResponseEntity.ok(response);
    }

    // ================== Request/Response DTOs ==================

    @lombok.Data
    public static class BalanceResponse {
        private UUID userId;
        private double cashBalance;
        private Map<Market, Long> holdings;
    }

    @lombok.Data
    public static class RegisterUserRequest {
        // userId is NOT accepted - it will be generated by UserService.addUser() from database
        private Double initialBalance;
        private Long initialBtc; // Optional: initial BTC holdings (currently not used)
    }

    @lombok.Data
    public static class DepositRequest {
        private double amount;
    }

    @lombok.Data
    public static class AddBtcRequest {
        private long amount;
    }
}

